# Emit scan.js v2: dual descriptors, int8-quantized colours, matcher metadata.
import base64, json, os, sys
import numpy as np
import scan_build2 as sb

WART = float(sys.argv[1]) if len(sys.argv) > 1 else 2.0
WCOL = 6.0

entries = sb.load_all()
print(f"emitting v2: {len(entries)} entries, wart={WART}")

rows = []
clipped = total = 0
for lang, num, wb, wc, ab, ac in entries:
    qw = np.clip(np.round(wc), -127, 127).astype(np.int8)
    qa = np.clip(np.round(ac), -127, 127).astype(np.int8)
    clipped += int((np.abs(wc) > 127).sum() + (np.abs(ac) > 127).sum())
    total += wc.size + ac.size
    rows.append(json.dumps([num, lang,
        base64.b64encode(wb.tobytes()).decode(),
        base64.b64encode(qw.tobytes()).decode(),
        base64.b64encode(ab.tobytes()).decode(),
        base64.b64encode(qa.tobytes()).decode()], separators=(",", ":")))
print(f"int8 clipping: {clipped}/{total} ({clipped/total:.2%})")

js = ("/* Card-scanner v2 descriptors: per reference scan (EN/FR/JP) a whole-card\n"
      "   AND an art-window dHash+colour pair, matched on-device with a\n"
      "   multi-hypothesis search. Generated by scan_emit2.py. */\n"
      f"const SCANDESC={{v:2,h:16,cg:{sb.CG},wcol:{WCOL},wart:{WART},"
      f"art:[{sb.ART[0]},{sb.ART[1]},{sb.ART[2]},{sb.ART[3]}],e:[\n"
      ) + ",\n".join(rows) + "\n]};\n"
out = r"C:\Users\nvanreet\Downloads\twm\scan.js"
open(out, "w", encoding="utf-8", newline="\n").write(js)
print(f"wrote {out}: {os.path.getsize(out)/1024:.0f} KB")
